[package]
name = "solana-instruction-fecther"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.10.36"
solana-sdk = "1.10.36"
solana-transaction-status = "1.10.35"
tokio = { version = "1.10", features = ["full"] }
config = "0.14.1"
base64 = "0.21.7"
